version: '3'
services:
    db.postgres:
        container_name: post
        image: postgres:9.4
        volumes:
          - ./psql-data:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=crmuser
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=crm
        ports:
          - '5432:5432'
    django:
        container_name: django_server
        build:
          context: ..
          dockerfile: ./oc-backend/Docker/Dockerfile
        image: owncrm
        stdin_open: true
        volumes:
          - ../crm:/project
        ports:
          - '8000:8000'
        depends_on:
          - db.postgres
    front:
        container_name: front
        build:
          context: ..
          dockerfile: ./oc-frontend/Dockerfile
        image: owncrm
        stdin_open: true
        volumes:
          - ../app
        ports:
          - '3000:3000'
volumes:
    postgres_data:




